path:
- k:/
- z:/
minerName:
apiKey: 43591456-0e31-4532-b591-ba71a60e28a9
log:
  lv: info
  path: ./log/
  name: miner.log
url:
  proxy: '""'
proxy:
    url: ''
    username: ''
    password: ''
language: cn
line: cn
extraParams:
  cpuIndex: ''
  disableDirectIo: 'false'
  flag: largepages,fullmem
  threadNum: '"2"'
